src/Entity/Contents.php
<?php

namespace App\Entity;

use App\Repository\ContentsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ContentsRepository::class)]
class Contents
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $title_fr = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $title_en = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description_fr = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description_en = null;

    #[ORM\OneToOne(mappedBy: 'content', cascade: ['persist', 'remove'])]
    private ?Spaces $spaces = null;

    #[ORM\OneToOne(mappedBy: 'content', cascade: ['persist', 'remove'])]
    private ?User $user = null;

    public function setTitle(string $language, ?string $title): self
    {
        $method = 'setTitle' . ucfirst(strtolower($language));
        if (method_exists($this, $method)) {
            $this->$method($title);
        }

        return $this;
    }

    public function setDescription(string $language, ?string $description): self
    {
        $method = 'setDescription' . ucfirst(strtolower($language));
        if (method_exists($this, $method)) {
            $this->$method($description);
        }

        return $this;
    }

    public function getTitleBasedOnLanguage($language) {
        $method = 'get' . 'title' . ucfirst(strtolower($language));

        if (method_exists($this, $method)) {
            return call_user_func([$this, $method]);
        } else {
            return "La méthode $method n'existe pas.";
        }
    }

    public function getDescriptionBasedOnLanguage($language) {
        $method = 'get' . 'Description' . ucfirst(strtolower($language));

        if (method_exists($this, $method)) {
            return call_user_func([$this, $method]);
        } else {
            return "La méthode $method n'existe pas.";
        }
    }
    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitleFr(): ?string
    {
        return $this->title_fr;
    }

    public function setTitleFr(?string $title_fr): static
    {
        $this->title_fr = $title_fr;

        return $this;
    }

    public function getTitleEn(): ?string
    {
        return $this->title_en;
    }

    public function setTitleEn(?string $title_en): static
    {
        $this->title_en = $title_en;

        return $this;
    }

    public function getDescriptionFr(): ?string
    {
        return $this->description_fr;
    }

    public function setDescriptionFr(?string $description_fr): static
    {
        $this->description_fr = $description_fr;

        return $this;
    }

    public function getDescriptionEn(): ?string
    {
        return $this->description_en;
    }

    public function setDescriptionEn(?string $description_en): static
    {
        $this->description_en = $description_en;

        return $this;
    }

    public function getDescriptionNl(): ?string
    {
        return $this->description_ne;
    }

    public function setDescriptionNl(?string $description_ne): static
    {
        $this->description_ne = $description_ne;

        return $this;
    }

    public function getSpaces(): ?Spaces
    {
        return $this->spaces;
    }

    public function setSpaces(?Spaces $spaces): static
    {
        // unset the owning side of the relation if necessary
        if ($spaces === null && $this->spaces !== null) {
            $this->spaces->setContent(null);
        }

        // set the owning side of the relation if necessary
        if ($spaces !== null && $spaces->getContent() !== $this) {
            $spaces->setContent($this);
        }

        $this->spaces = $spaces;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        // unset the owning side of the relation if necessary
        if ($user === null && $this->user !== null) {
            $this->user->setContent(null);
        }

        // set the owning side of the relation if necessary
        if ($user !== null && $user->getContent() !== $this) {
            $user->setContent($this);
        }

        $this->user = $user;

        return $this;
    }
}

src/Controller/DashboardHostController.php
<?php

namespace App\Controller;


use Exception;
use App\Entity\Images;
use App\Entity\Spaces;
use App\Entity\Reservations;
use App\DTO\FormEditSpaceModel;
use App\Services\PictureServices;
use App\Repository\UserRepository;
use App\Repository\SpacesRepository;
use App\Form\Combined\FormEditSpaceType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Exception\UserNotAuthenticatedException;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class DashboardHostController extends AbstractController
{
    public function __construct(Private EntityManagerInterface $entityManager) {
        $this->entityManager = $entityManager;
    }
    #[Route('/owner/annonces', name: 'dashboard_host_annonces')]
    public function annonce(
        Request $request,
    ): Response {
        try {
            if (!$this->getUser()) {
                throw new UserNotAuthenticatedException("L'utilisateur doit être connecté pour accéder à la page.");
            }
        } catch (UserNotAuthenticatedException $e) {
            $request->getSession()->set('errorMessage', $e->getMessage());
            return $this->redirectToRoute('app_error_403');
        }
        
        return $this->render('dashboard_host/annonces.html.twig');
    }

    #[Route('/owner/reservations', name: 'dashboard_host_reservations')]
    public function reservation(
        Request $request,
    ): Response {
        try {
            if (!$this->getUser()) {
                throw new UserNotAuthenticatedException("L'utilisateur doit être connecté pour accéder à la page.");
            }
        } catch (UserNotAuthenticatedException $e) {
            $request->getSession()->set('errorMessage', $e->getMessage());
            return $this->redirectToRoute('app_error_403');
        }

        $allSpaces = $this->entityManager->getRepository(Spaces::class)->findBy(['ownedByUser' => $this->getUser()->getId()]);

        $reservations = [];
        // dd($allSpaces);
        foreach ($allSpaces as $space) {
            // dd($space->getReservation());
            foreach ($space->getReservations() as $reservation) {
                $reservations[] = $reservation;
            }
        }
        
        return $this->render('dashboard_host/reservations.html.twig', [
            'reservations' => $reservations,
            'userBookings' => $this->entityManager->getRepository(Reservations::class)->findBy(['user' => $this->getUser()->getId()]),
        ]);
    }

    #[Route('/owner/edit/{id}', name: 'dashboard_host_edit')]
    public function edit(
        Request $request,
        Spaces $space,
        EntityManagerInterface $entityManager,
        PictureServices $pictureService,
        SpacesRepository $spacesRepository,
        UserRepository $userRepository,
    ): Response {

        try {

            if (!$this->getUser()) {
                throw new UserNotAuthenticatedException("L'utilisateur doit être connecté pour accéder à la page.");
            }

            if ($this->getUser() != $space->getOwnedByUser() ) {
                throw new Exception("Accès refusé : Vous tentez d'accéder à une page réservée à un autre utilisateur.");
            }

        } catch (UserNotAuthenticatedException $e) {
            
            $request->getSession()->set('errorMessage', $e->getMessage());
            
            return $this->redirectToRoute('app_error_403');
        } catch (Exception $e) {
            
            $request->getSession()->set('errorMessage', $e->getMessage());
            
            return $this->redirectToRoute('app_error_403');
        }

        // if (!$this->getUser()) return $this->redirectToRoute('public_home');
        // if (!$space->getOwnedByUser() == $this->getUser()) return $this->redirectToRoute('public_home');

        $galleries = $entityManager->getRepository(Images::class)->findBy(['spaces' => $space->getId()], ['sortOrder' => 'ASC']);
        
        $user = $space->getOwnedByUser();
        $DTO_MODEL = new FormEditSpaceModel();
        // dd($space);
        $DTO_MODEL->hydrate($space);
        // dd($DTO_MODEL);
        $form = $this->createForm(FormEditSpaceType::class, $DTO_MODEL);
        // Si vous voulez définir la valeur du champ status basée sur une propriété du $user
        $statusFromUser = $user->getStatus();
        if ($statusFromUser) {
            $form->get('amenity')->get('status')->setData($statusFromUser);
        } else {
            $form->get('amenity')->get('status')->setData('Particulier');
        }
        
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $status = $request->request->all()['form_edit_space']['amenity']['status'];
            $adresse =  $form->getData()->getAdresse();
            $equipments =  $form->getData()->getAmenity();
            // $adresse =  $form->getData()->getAdresse();
            // dd($form, $form->getData()->getAdresse());
            if (isset($_POST['images'])) {
                $oldOrder = $_POST['images'];
                $newOrder = [];
    
                foreach($oldOrder as $key => $value) {
                    $imageEntity = $entityManager->getRepository(Images::class)->findOneBy(['id' => $key]);
    
                    $imageEntity->setSortOrder($value);
                    $entityManager->persist($imageEntity);
                    $entityManager->flush();
                }
            }
            // dd($form, $form->getData()->getSpace(), $space);
            if ($form->getData()->getGalleries()->getImagePath()) {
                $this->handleNewImages($form, $request, $pictureService, $entityManager);
                
            }
            $form->getData()->getAdresse();

            $this->entityManager->persist($adresse);
            // $this->entityManager->flush();

            $space->setAdresse($adresse);
            $space->addAmenty($equipments);
            $userRepository->save($user);
            $spacesRepository->save($space);
            return $this->redirectToRoute('dashboard_host_annonces', [], Response::HTTP_SEE_OTHER);
        }
        
        return $this->render('dashboard_host/edit.html.twig', compact('space', 'form', 'galleries'));
    }

    private function handleNewImages($dataArray, $request, $pictureService, EntityManagerInterface $entityManager) {
        $folder = 'Archives/Spaces/' . $dataArray->getData()->getSpace()->getId() . '/Galleries';
        $initialOrder = count($entityManager->getRepository(Images::class)->findBy(['space' =>  $dataArray->getData()->getSpace()]));
        $dataImage = $request->files->all()['form_edit_space']['galleries']['imagePath'];
        $fichier = $pictureService->add($dataImage, $folder);
        
        $order = $initialOrder + 1;

        // Create a new Image object for each file
        $image = new Images();
        $image->setSpaces($dataArray->getData()->getSpace());
        $image->setImagePath($fichier);
        $image->setSortOrder($order);
        
        $entityManager->persist($image);
        $entityManager->flush();
    }
}

templates/dashboard_host/edit/_address-section.html.twig
<div class="address-section">

    {{ form_label(form.adresse, 'Address'|trans, {
        'label_attr': {'class': 'section-header'}
    }) }}

    <div class="address-inputs">
        {{ form_row(form.adresse.country, {
            'row_attr': {'class': 'address-input-set'},
            'label': 'Country'|trans,
            'label_attr': {'class': 'address-label'},
            'attr': {'class': 'country-select'}
        }) }}
        
        {{ form_row(form.adresse.city, {
            'row_attr': {'class': 'address-input-set'},
            'label': 'City'|trans,
            'label_attr': {'class': 'address-label'},
            'attr': {'class': 'city-input'}
        }) }}
        
        {{ form_row(form.adresse.street, {
            'row_attr': {'class': 'address-input-set'},
            'label': 'Street'|trans,
            'label_attr': {'class': 'address-label'},
            'attr': {'class': 'street-input'}
        }) }}
        
        {{ form_row(form.adresse.streetNumber, {
            'row_attr': {'class': 'address-input-set'},
            'label': 'Street number'|trans,
            'label_attr': {'class': 'address-label'},
            'attr': {'class': 'number-input'}
        }) }}
        
        {{ form_row(form.adresse.postalCode, {
            'row_attr': {'class': 'address-input-set'},
            'label': 'Postal code'|trans,
            'label_attr': {'class': 'address-label'},
            'attr': {'class': 'postal-code-input'}
        }) }}
    </div>

</div>

templates/dashboard_host/edit/_equipment-section.html.twig
<div class="equipment-section">
    {{ form_label(form.amenity, 'Amenities'|trans, {
        'label_attr': {'class': 'section-header'}
    }) }}

    <div class="equipment-inputs">
        {{ form_row(form.amenity.status, {
            'row_attr': {'class': 'status-input-set'},
            'label': 'Status'|trans,
            'label_attr': {'class': 'status-label'},
            'attr': {'class': 'status-options'}
        }) }}

        {{ form_row(form.amenity.amenities, {
            'row_attr': {'class': 'space-equipment-input-set'},
            'label': 'Amenity'|trans,
            'label_attr': {'class': 'equipment-label'},
            'attr': {'class': 'equipment-options'}
        }) }}
    </div>
</div>

templates/dashboard_host/edit/_gallerie-section.html.twig
<div class="galleries-section">
    {{ form_label(form.galleries, 'Gallerie', {
        'label_attr': {'class': 'section-header'}
    }) }}
    <div>
        {% if space.image %}
            {% for image in galleries %}
                {% if image.sortOrder != 21 %}
                <div class="dropzone">
                    <img src="{{ asset('assets/uploads/' ~ space.file ~ '/' ~ image.imagePath) }}" class="draggable" draggable="true" data-id="{{ image.id }}" alt="">
                </div>
                {% endif %}
            {% endfor %}
        {% endif %}
        {{ form_row(form.galleries) }}
        
        <div id="hiddenFields">
            <!-- Les champs cachés seront insérés ici -->
        </div>
    </div>
</div>

templates/dashboard_host/edit/_language-section.html.twig
<div class="language-section">
    <div class="language-buttons">
        <button class="language-btn language-btn-en">{{ 'English version'|trans }}</button>
        <button class="language-btn language-btn-fr active">{{ 'French version'|trans }}</button>
    </div>

    <div class="title-description-section">
        {{ form_label(form.content, 'Title & Description'|trans, {
            'label_attr': {'class': 'section-header'}
        }) }}

        <div class="title-description-inputs">
            {{ form_row(form.content.titleEn, {
                'row_attr': {'class': 'title-input-set'},
                'label': 'Title'|trans,
                'label_attr': {'class': 'title-label'},
                'attr': {'class': 'title-input'}
            }) }}
            
            {{ form_row(form.content.titleFr, {
                'row_attr': {'class': 'title-input-set active'},
                'label': 'Title'|trans,
                'label_attr': {'class': 'title-label'},
                'attr': {'class': 'title-input'}
            }) }}

            {{ form_row(form.content.descriptionEn, {
                'row_attr': {'class': 'description-textarea-set'},
                'label': 'Description'|trans,
                'label_attr': {'class': 'description-label'},
                'attr': {'class': 'description-textarea'}
            }) }}
            
            {{ form_row(form.content.descriptionFr, {
                'row_attr': {'class': 'description-textarea-set active'},
                'label': 'Description'|trans,
                'label_attr': {'class': 'description-label'},
                'attr': {'class': 'description-textarea'}
            }) }}
        </div>
    </div>
</div>

templates/dashboard_host/edit/_price-category-section.html.twig
<div class="price-category-section">
    {{ form_label(form.space, 'Price & Category'|trans, {
        'label_attr': {'class': 'section-header'}
    }) }}

    <div class="price-category-inputs">
        {{ form_row(form.space.type, {
            'row_attr': {'class': 'category-input-set'},
            'label': 'Type',
            'label_attr': {'class': 'category-label'},
            'attr': {'class': 'category-select'}
        }) }}
        
        {{ form_row(form.space.price, {
            'row_attr': {'class': 'price-input-set'},
            'label': 'Price'|trans,
            'label_attr': {'class': 'price-label'},
            'attr': {'class': 'price-input'}
        }) }}
    </div>
</div>